Adding support for DALEX package
mayer79/shapviz pull request #61
Opened 2023-03-15 15:36 UTC by adrianstando

Issue #60

2023-03-17 17:01 UTC, mayer79 commented on R/shapviz_methods.R
We actually do not need to care about the "collapse" logic. It modifies the input X on initialization. Afterward, the shapviz objects forget about it. So also no need for a `get_collapse()` function.

2023-03-17 18:27 UTC, mayer79 requested changes
Not fully through yet, but this is a good start :-)

2023-03-17 20:43 UTC, adrianstando commented on R/shapviz_methods.R
Okay, I see it. I believed it is stored as an attribute

2023-03-17 21:14 UTC, mayer79 approved these changes
One function to finish, otherwise looks good to me, thanks!

2023-03-17 21:14 UTC, mayer79 commented on R/shapviz.R
> +}
```suggestion
shapviz.predict_parts <- function(object, ...) {
  if (!inherits(object, c("shap", "shap_aggregated", "break_down"))) {
    stop("Incorrect object! It is neither 'shap', 'shap_aggregated' nor 'break_down'!")
  }
  if (inherits(object, "shap")) {
    agg <- as.data.frame(object[object$B == 0, ])
    baseline <- attr(object, "intercept")
  } else {
    if (inherits(object, "shap_aggregated")) {
      agg <- object$aggregated
    } else {  # break_down
      agg <- as.data.frame(object)  # to drop additional classes
    }
    baseline <- agg[1L, "contribution"]
    agg <- agg[2:(nrow(agg) - 1L), ]     # Drop intercept and prediction
  }

  ## Problem: agg might contain all feature values as strings
  ## -> excludes sv_dependence() and beeswarms
  X <- data.frame(t(agg[["variable_value"]]))
  S <- t(agg[["contribution"]])
  colnames(X) <- colnames(S) <- agg[["variable_name"]]

  shapviz(shaps, X = X, baseline = baseline, ...)
}
```

2023-03-17 21:14 UTC, mayer79 commented on R/shapviz.R
> +}
My try to get used to predict_parts() ;). Will need a short review from your side. Rest looks fine!

2023-03-18 13:37 UTC, adrianstando commented on R/shapviz.R
> +}
I think this version of the function looks better :) 
Only **shaps** object in the last line has to be changed to **S**, but I will fix this with next commit.

2023-03-24 20:35 UTC, mayer79 commented
LGTM

2023-03-24 20:35 UTC, merged